# (Gruvbox Material Dark Medium) {{{
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
# }}}
# {{{ Forest Night
# colors:
#   primary:
#     background: '0x323d43'
#     foreground: '0xd8caac'
#
#   normal:
#     black:   '0x868d80'
#     red:     '0xe68183'
#     green:   '0xa7c080'
#     yellow:  '0xd9bb80'
#     blue:    '0x89beba'
#     magenta: '0xd3a0bc'
#     cyan:    '0x87c095'
#     white:   '0xd8caac'
#
#   bright:
#     black:   '0x868d80'
#     red:     '0xe68183'
#     green:   '0xa7c080'
#     yellow:  '0xd9bb80'
#     blue:    '0x89beba'
#     magenta: '0xd3a0bc'
#     cyan:    '0x87c095'
#     white:   '0xd8caac'
# }}}

window:
  # 启动时最大化
  startup_mode: 'Maximized'

background_opacity: 0.65

font:
  normal:
    family: source code pro
    style: regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold_Italic

key_bindings:
  - {key: I, mods: Alt, action: PasteSelection}
  - {key: C, mods: Control, action: Copy}
    # NOTE:
    # FIXME:
    # TODO:
    # BUG:
