# Colors (Gruvbox Material Dark Medium)
# {{{
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
# }}}

window:
  startup_mode: 'Maximized'

background_opacity: 0.65

font:
  normal:
    family: 'Sauce Code Pro Nerd Font'
  bold:
    family: 'Sauce Code Pro Nerd Font Bold'
    # family: 'Hack Bold'
    # family: 'Monospace Bold'
    # family: 'ubuntu mono bold'
  italic:
    family: 'Sauce Code Pro Nerd Font Italic'
  bold_italic:
    family: 'Sauce Code Pro Nerd Fond Bold Italic'

key_bindings:
  - {key: I, mods: Alt, action: PasteSelection}
  - {key: C, mods: Control, action: Copy}
    # NOTE:
    # FIXME:
    # TODO:
    # BUG:
