#!/bin/sh

# 系统类型
system_type=$(uname -s)
# 包管理器名字
# pkg=


setup_ubuntu_environment() {

    echo "updating packages..."
    sudo apt update && sudo apt -y upgrade
    echo "Installing required packages..."
    sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

    echo "setuping basic packages..."
    sudo apt install -y nodejs npm python3-pip zsh lua5.3
    # 更新pip3版本
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python3 get-pip.py
    # 更新node版本
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable
    # 安装pyenv
    bash ~/installers/pyenv-installer.sh


    echo "installing via snap..."
    sudo snap install nvim --classic
    sudo snap install ccls --classic
    sudo snap install universal-ctags

    echo "installing applications"
    sudo apt install -y trash-cli nnn gdb-dashboard
    # 安装zeal
    sudo add-apt-repository ppa:zeal-developers/ppa -y && sudo apt-get update && sudo apt-get install -y zeal

    echo "installing linter and checker"
    sudo npm install -g eslint && sudo npm install -g prettier
    sudo pip3 install pylint && sudo pip3 install autopep8
    sudo apt install cppcheck -y && sudo npm install -g clang-format

    echo "installing neovim-remote"
    pip3 install neovim-remote

    echo "installing GNU GLOBAL (gtags)"
    # 安装依赖
    sudo apt install -y libncurses5-dev libncursesw5-dev
    wget https://ftp.gnu.org/pub/gnu/global/global-6.6.tar.gz
    tar xvf global-6.6.tar.gz
    cd global-6.6/
    ./configure && make && sudo make install
    cd ~ && rm -r global-6.6/ && rm global-6.6.tar.gz

    echo "installing riggrep"
    curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb && sudo dpkg -i ripgrep_11.0.2_amd64.deb
    rm ripgrep_11.0.2_amd64.deb

    echo "installing tmux"
    # gawk　是tmux-finger插件的依赖
    sudo apt install -y gawk tmux
    # 安装tpm
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    echo "installing zgen..."
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

    # NOTE: 最好放在最后，因为需要手动确认配置
    echo "Installing fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

    echo "Installing neovim plugins with vim-plug..."
    nvim "+PlugUpdate" "+PlugClean!" "+PlugUpdate" "+qall"

    echo "Installing alacritty"
    # 添加ppa
    sudo add-apt-repository ppa:mmstick76/alacritty -y
    # 添加缺失的public key
    sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+="$key"; fi; done
    sudo apt-get update && sudo apt install -y alacritty


    echo "更换默认bash为zsh..."
    chsh -s /bin/zsh

    bash ~/.yadm/check_commands.sh
    echo "需要重启系统使终端和shell配置生效"
    confirm_reboot

}

confirm_reboot() {
    while true
    do
    echo -n "Are you sure to reboot now? (y/n):"
    read crm
    if [ "$crm"x = "y"x ]; then
        echo "rebooting"
        \reboot
    else
        break
    fi
    break
    done
}

echo "starting bootstrap..."
if [ "$system_type" = "Linux" ]; then
    setup_ubuntu_environment
fi
